steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/thinking-glass-351217/bhargav-100932523/$COMMIT_SHA',
        '.'
      ]

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/thinking-glass-351217/bhargav-100932523/$COMMIT_SHA'
      ]
  
images:
  - 'us-central1-docker.pkg.dev/thinking-glass-351217/bhargav-100932523/$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
